import { CalendarEvent, CampusEvent, Task, UserProfile } from './types';

export const initialProfile: UserProfile = {
  name: 'Niharika Adhikari',
  major: 'Computer Science Major',
  classYear: "Class of '27",
  academicStanding: 'Junior',
  honors: 'Honor Roll',
  studentId: '#40928',
  streakDays: 5,
  streakLevel: 4,
  weeklyStreak: [
    { day: 'M', state: 'done' },
    { day: 'T', state: 'done' },
    { day: 'W', state: 'done' },
    { day: 'T', state: 'done' },
    { day: 'F', state: 'done' },
    { day: 'S', state: 'active' },
    { day: 'S', state: 'locked' },
  ],
  weeklyAnalytics: {
    tasksDone: 24,
    tasksDoneDiff: '+15% vs lw',
    studyLoggedHours: 18.5,
    studyCampusRank: 'Top 10% campus',
    onTimeRate: 92,
    onTimeSubtext: '23 of 25 deadlines',
    targetGpa: '3.80',
    currentGpa: '3.84',
    gpaStatus: 'On Track',
  },
  avatarUrl:
    'https://lh3.googleusercontent.com/aida/AEtjO1URUuRwIVbtswsnib_CPCbEXMEprKwOIYf24utJA5i4pw0jNrATqHdV8KIRc1KIRoOabivQqjg2KPQUfvgUyWDFu_-55dzqGTNHyoSaHB95nJC-Hij4YojJumVfuOzksTzIF2lfKImKM22kbd9ZhQV-85zAsH9DcKFtv3WkQKm7IggZIC3FU1mA4FlzqjiSYAAH3zai6J8VXQDC-jlqhTMtbSw2Z4GnuM0vNKMUxaZ3jBtSQsdMbMQoyts',
  enrolledCourses: ['CS 301', 'MATH 240', 'ENG 102', 'BIO 110'],
  notificationPreference: 'Daily briefing at 8:00 AM',
  syncCalendars: 'Google & Outlook connected',
  darkMode: false,
};

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Research Paper Draft',
    description: 'Finalize thesis statement, synthesize 6 JSTOR references for English lit review.',
    course: 'ENG 110',
    categorySection: 'overdue',
    dueDateText: 'Yesterday',
    priority: 'High',
    completed: false,
    collaborator: 'TA',
  },
  {
    id: 'task-2',
    title: 'Lab Report #3: Pointer Trees',
    description: 'Run benchmark test suites and export final memory leak analysis.',
    course: 'CS 101',
    categorySection: 'today',
    dueDateText: 'Due 5:00 PM',
    priority: 'High',
    completed: false,
    subtasks: [
      { id: 'sub-1', title: 'Compile AVL benchmark binaries', completed: true },
      { id: 'sub-2', title: 'Valgrind heap memory audit', completed: true },
      { id: 'sub-3', title: 'Plot throughput diagrams', completed: false },
      { id: 'sub-4', title: 'Format PDF lab submission', completed: false },
    ],
    commentsCount: 3,
  },
  {
    id: 'task-3',
    title: 'Read Chapter 5 – Linear Transformations',
    description: 'Complete practice problems 5.1 to 5.8 on eigenvalues.',
    course: 'MATH 201',
    categorySection: 'today',
    dueDateText: 'Due 11:59 PM',
    priority: 'Med',
    completed: false,
    attachment: 'Ch5_notes.pdf',
  },
  {
    id: 'task-4',
    title: 'CS101 Midterm Quiz',
    description: 'Chapters 1–4 Multiple Choice',
    course: 'CS 101',
    categorySection: 'today',
    dueDateText: 'Due in 2h',
    priority: 'High',
    completed: false,
  },
  {
    id: 'task-5',
    title: 'Calculus Problem Set 4',
    description: 'Integration by Parts & Trig',
    course: 'MATH 201',
    categorySection: 'today',
    dueDateText: 'Due Today, 11:59 PM',
    priority: 'Med',
    completed: false,
  },
  {
    id: 'task-6',
    title: 'Algorithm Problem Set 5',
    description: 'Dynamic Programming graph optimization techniques.',
    course: 'CS 101',
    categorySection: 'upcoming',
    dueDateText: 'Tomorrow, 2:00 PM',
    priority: 'Medium Priority',
    completed: false,
  },
  {
    id: 'task-7',
    title: 'Literature Review Draft',
    description: 'Modern Narrative Analysis',
    course: 'ENG 110',
    categorySection: 'upcoming',
    dueDateText: 'Due Tomorrow, 5 PM',
    priority: 'Normal',
    completed: false,
  },
  {
    id: 'task-8',
    title: 'Register for Spring Classes',
    description: 'Finalize semester degree plan and lock elective credits with advisor approval.',
    course: 'Personal',
    categorySection: 'completed',
    dueDateText: 'Completed 9:30 AM',
    priority: 'Normal',
    completed: true,
    completedAtText: 'Completed 9:30 AM',
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'Database Systems Lecture',
    timeRange: '09:00 AM – 10:30 AM',
    startHour: 9,
    durationLabel: '90 min',
    type: 'lecture',
    typeTag: 'CS 301 • Lecture',
    location: 'Hall 101',
    instructor: {
      name: 'Prof. Miller',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDiWqodmUIHWwhhlXxlizQmfUjiOuODbJpT40lPeXwWcqYNx592igvZzgX-XSfgq55RhRV4Hx8DZzeW2FganXoIg5nFuNhYuSjQD_UpH1CG-o9eBU6HZP0OPyP6OLLX_E9FcYJr0FDD6t0hclZf6xsFusa_oV7H9847Gm2dSEy9pAZFji87QmIkhyhjRFhd_T-NX1UWkr89vXw7OQ8vgl7Z4r-pjo54_JIYJGmmiALLVY38D5mGHyqP',
    },
    dayIndex: 3, // Thursday Oct 1
  },
  {
    id: 'cal-2',
    title: 'Group Study Session',
    timeRange: '11:00 AM – 12:00 PM',
    startHour: 11,
    durationLabel: '60 min',
    type: 'study_group',
    typeTag: 'Study Group',
    location: 'Library Room B',
    locationDetail: 'Table 4',
    membersCount: 4,
    dayIndex: 3, // Thursday Oct 1
  },
  {
    id: 'cal-3',
    title: 'Lunch & Campus Walk',
    timeRange: '01:00 PM – 01:45 PM',
    startHour: 13,
    durationLabel: '45 min free interval',
    type: 'free_interval',
    typeTag: 'Break',
    location: 'Campus Quad Lawn & Dining Hall',
    dayIndex: 3,
  },
  {
    id: 'cal-4',
    title: 'Linear Algebra Seminar',
    timeRange: '02:00 PM – 03:30 PM',
    startHour: 14,
    durationLabel: '90 min',
    type: 'seminar',
    typeTag: 'MATH 201 • Seminar',
    location: 'Math Building 202',
    instructor: {
      name: 'Dr. Alistair',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDjUm9yf2K6lX0XMdW_Upx0-ffnN9PnMblS5lPWWmldk3XsmDhwwIoe6GOo_jlpFeZrZwYZtbpEwP0dmb1ikUz2dWEgF3WLrbsdykrz7hoBlIs005h41_qxX1Im7f6Z4_6rgNreU8n57SPpQPLlOlARAmym-x3AryfMYkSZV9vRisg2zxhShL4WxYiTUd4cNjIsNUaoBIPC8cBKGv8ukLGQH2gGDCoFX9JZHTVToAb5X0KkTpXULDYp',
    },
    dayIndex: 3,
  },
  {
    id: 'cal-5',
    title: 'Prof. Chen • Room 304',
    timeRange: '04:00 PM – 05:00 PM',
    startHour: 16,
    durationLabel: 'Upcoming',
    type: 'office_hours',
    typeTag: 'Office Hours',
    location: 'Science Building Room 304',
    notes: 'Drop-in questions for Midterm review',
    dayIndex: 3,
  },
  // Supporting schedule entries for other days
  {
    id: 'cal-6',
    title: 'Algorithms & Data Structures',
    timeRange: '10:00 AM – 11:30 AM',
    startHour: 10,
    durationLabel: '90 min',
    type: 'lecture',
    typeTag: 'CS 101 • Lecture',
    location: 'Room 304',
    instructor: {
      name: 'Prof. Chen',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBPpq2sG4howP4_MBqGwE5i46vYi8869zEuZCnnczQ0iUW7RJWkK2tg4wQYyzPwQGnO6zpXEvsaRxMw8BNRGE0Racd15dAJz_FOfi8I3dKJ80mc9C9TaVbu4k779l5pRpERgmW2DCLyHZJgFY-zy1eoGHjaWgSz39WeUrCUovVukfARehO3MNeypRenrpyw145ft0WW8rXpCZqLVo4teY7okrMkJ7Sg2lFcWF6wlXFHnkEFkWkgjQ1W',
    },
    dayIndex: 0, // Mon 28
  },
  {
    id: 'cal-7',
    title: 'UI/UX Design Workshop',
    timeRange: '01:00 PM – 02:30 PM',
    startHour: 13,
    durationLabel: '90 min',
    type: 'seminar',
    typeTag: 'Design Studio',
    location: 'Studio B',
    membersCount: 12,
    dayIndex: 1, // Tue 29
  },
  {
    id: 'cal-8',
    title: 'Modern Literature Colloquium',
    timeRange: '02:00 PM – 03:30 PM',
    startHour: 14,
    durationLabel: '90 min',
    type: 'lecture',
    typeTag: 'ENG 110',
    location: 'Humanities Hall 210',
    dayIndex: 2, // Wed 30
  },
  {
    id: 'cal-9',
    title: 'Cellular Biology Lab Session',
    timeRange: '09:00 AM – 11:00 AM',
    startHour: 9,
    durationLabel: '120 min',
    type: 'lecture',
    typeTag: 'BIO 110 • Lab',
    location: 'BioMed Wing 104',
    dayIndex: 4, // Fri 2
  },
];

export const initialCampusEvents: CampusEvent[] = [
  {
    id: 'evt-1',
    title: 'Annual Campus Hackathon 2026',
    category: 'Clubs',
    categoryLabel: 'Featured Flagship',
    dateTag: 'OCT 10',
    fullDateTime: 'Sat, Oct 10 • 9:00 AM • Student Union Grand Hall',
    location: 'Student Union Grand Hall',
    attendeesCount: 350,
    attendeesAvatars: ['JD', 'SK', 'AL'],
    isFeatured: true,
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDZXuN80MyF5fGdWB3CSISL8r4uuq3bzmS5kRhpgwtmyJcoWttVYXJ4VmsisX8DFRqGSGmw4Fi4q5bbYdYjrPJQGEcM-35RSX0xbyCPch1R-I0zT6cgclWC2ADymrVXG2KwQ1QU0Q1iyx3G7SWPl1Jabf-HH9XrNX2-9konCmL1JI1DgrvM4PL2N5cF-BA1U0usueXKDg-BH6kEH_lPK-m31N8ahuRuilad-DYfDXThndzRdeu6uk58',
    rsvpStatus: false,
    isSaved: true,
    description:
      '36-hour sprint gathering software engineers, designers, and innovators across campus. $10,000 in prizes, mentor office hours, free food, and direct recruiter interviews.',
    organizer: 'Computer Science Society & ACM Chapter',
  },
  {
    id: 'evt-2',
    title: 'AI & Future of Tech Guest Lecture',
    category: 'Academic',
    categoryLabel: 'Academic • Tech Club',
    dateTag: 'OCT 2',
    fullDateTime: 'Fri, Oct 2 • 4:00 PM | Hall B',
    location: 'Hall B (Science Auditorium)',
    attendeesCount: 42,
    attendeesAvatars: ['R', 'M'],
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAEc_PUbEM1BVzXYlrvaWcn9IRPp9mZj2MTHjZzqg944EPdkuvhVjz5bB26VNBLqT0xY1TEEEIr8jJuuaetmSKoDATH-qMehN-mY2YwCLXX2oq8o3f2xjs74oQuEx6FBuRT7c5Fnq6E9QY_w-E9HkMuXZEMUFbmK7MqPR9lTpZjcHZmQzXtbny6OHSff6uQ5dOr1FUl2jmeX6kFVKuAIzBhakB7aAZDp3kenAd4tKc99n08GR_Ec6M2',
    rsvpStatus: false,
    isSaved: false,
    description:
      'Exploring the intersection of humanity, foundational frontier models, and next-generation robotics with visiting Silicon Valley industry researchers.',
    organizer: 'Robotics & Artificial Intelligence Student Alliance',
  },
  {
    id: 'evt-3',
    title: 'Fall Campus Music Festival',
    category: 'Social & Parties',
    categoryLabel: 'Social & Live Music',
    dateTag: 'OCT 3',
    fullDateTime: 'Sat, Oct 3 • 6:00 PM | Quad Lawn',
    location: 'Quad Lawn Main Amphitheater',
    attendeesCount: 128,
    attendeesAvatars: ['K', 'T', 'E'],
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAP7crwiug-DQpj9cNDSiJ5vOTMjukILTs6mTCOFGkjsTl2k5Nk7O1i8_Im_-LOT52jZIs20VN8RP6EswkQJC2gE3zhU5TlB0RY8JqLzZh00SSlCw3G0GGduZARnPK6zYhM-vQULH9pu6U1-Zebbf2rycIGgwlXaetyYtdtFw_K5tKvMZpDIcCcTOhcyMEcaS9d5nUjnYJ7dQEYxT4Qfu4Xnx-ku8wRI0GhBh5X7JrmldflOM_YeKlo',
    rsvpStatus: false,
    isSaved: false,
    description:
      'Live student band performances, local artisan food trucks, warm cider, and seasonal autumn celebration under the campus lights.',
    organizer: 'Campus Activity Board & Music Collective',
  },
  {
    id: 'evt-4',
    title: 'Design Thinking Sprint',
    category: 'Clubs',
    categoryLabel: 'Workshop • UI/UX Society',
    dateTag: 'SUN, OCT 4',
    fullDateTime: 'Sun, Oct 4 • 2:00 PM | Design Lab 102',
    location: 'Design Lab 102',
    attendeesCount: 19,
    attendeesAvatars: ['L', 'N'],
    iconName: 'palette',
    rsvpStatus: false,
    isSaved: false,
    description:
      'Hands-on interactive design workshop tackling real campus navigation problems using Figma, rapid prototyping, and user interviewing frameworks.',
    organizer: 'UI/UX Society',
  },
  {
    id: 'evt-5',
    title: 'Tech Career Fair & Resume Clinic',
    category: 'Career',
    categoryLabel: 'Career • Placement Cell',
    dateTag: 'OCT 8',
    fullDateTime: 'Thu, Oct 8 • 11:00 AM | Sports Complex Arena',
    location: 'Sports Complex Arena',
    attendeesCount: 215,
    attendeesAvatars: ['S', 'D', 'W'],
    iconName: 'work',
    rsvpStatus: false,
    isSaved: true,
    description:
      'Over 40 top engineering and design companies hiring for summer internships and full-time new-grad positions. Free professional headshots included.',
    organizer: 'University Career Center',
  },
];

export const courseDetails = [
  {
    code: 'CS 301',
    name: 'Database Management Systems',
    instructor: 'Prof. Miller',
    credits: 4,
    schedule: 'Tue, Thu 09:00 AM – 10:30 AM',
    location: 'Hall 101',
    syllabusUrl: '#',
    grade: 'A-',
    color: '#6063ee',
  },
  {
    code: 'MATH 201',
    name: 'Linear Algebra & Matrix Theory',
    instructor: 'Dr. Alistair',
    credits: 4,
    schedule: 'Tue, Thu 02:00 PM – 03:30 PM',
    location: 'Math Building 202',
    syllabusUrl: '#',
    grade: 'A',
    color: '#e29100',
  },
  {
    code: 'ENG 110',
    name: 'Critical Reading and Composition',
    instructor: 'Dr. Eleanor Vance',
    credits: 3,
    schedule: 'Mon, Wed 02:00 PM – 03:30 PM',
    location: 'Humanities Hall 210',
    syllabusUrl: '#',
    grade: 'B+',
    color: '#4648d4',
  },
  {
    code: 'BIO 110',
    name: 'Cellular and Molecular Foundations',
    instructor: 'Prof. Marcus Chen',
    credits: 4,
    schedule: 'Wed, Fri 09:00 AM – 11:00 AM',
    location: 'BioMed Wing 104',
    syllabusUrl: '#',
    grade: 'A',
    color: '#10b981',
  },
];
